### ISSUE TITLE
Train Ticket Locust File

### ISSUE THREAD

**Issue by jessberg** [pptam/pptam-tool#48]
I am using the locust file made for Train Ticket and I was wondering why many things toward the bottom were commented out.  Are these valid tasks?  Why were they removed?

**Comment by ajanes** [comment]
Sorry, this modification was done by mistake. I restored it. If you check now, everything should be fine. All functions work, we use a matrix to define transition probabilities between functions that work (expected) and functions that are supposed to fail (unexpected) to test if the system can handle that. If you have questions about using that file, don't hesitate to write!
