### ISSUE TITLE
Could I use pptam to test load test trainticket on k8s

### ISSUE THREAD

**Issue by Zenghao-CQ** [pptam/pptam-tool#50]
Hi ajane, thanks for your great work on opensource such a great project! Now, i am trying to load test trainticket on a k8s cluster, and i noticed that in your intasll scripts, i have to:

1. init a docker swarm swarm
2. change user to vagrant

Are these 2 steps specific for benchmarks running on docker swarm? If so, could i just skipp those 2 steps on a k8s cluster?

**Comment by ajanes** [comment]
Hi! Thanks for passing by our project :) I have to say that this repository is ongoing work and we are storing here different approaches. Vagrant is only needed if you want to test the approach locally. Vagrant will create 2 virtual machines and install the system. If you want to deploy trainticket to k8s, probably you should use the k8s installation that is already part of Trainticket. To do load testing you now have 2 possibilities. You use locust.io manually, or you use PPTAM to conduct a series of experiements. What do you want to do?

**Comment by Zenghao-CQ** [comment]
> 
Hi! Thanks for answering my question,  I think i will reuse your locust.io scripts to generate load. Thanks for ur help again!




> Hi! Thanks for passing by our project :) I have to say that this repository is ongoing work and we are storing here different approaches. Vagrant is only needed if you want to test the approach locally. Vagrant will create 2 virtual machines and install the system. If you want to deploy trainticket to k8s, probably you should use the k8s installation that is already part of Trainticket. To do load testing you now have 2 possibilities. You use locust.io manually, or you use PPTAM to conduct a series of experiements. What do you want to do?
> 
> To be clear: I assume you want to do performance testing. If you want to do some other type of test, follow the k8s instructions to install TrainTicket and go on from there :)

**Comment by ajanes** [comment]
Perfect, but please, if you work on a publication, cite one of our works, e.g. https://www.sciencedirect.com/science/article/abs/pii/S016412122200142X. Thank you!
