### ISSUE TITLE
Could I just use the locust to run the locustfile.py ? Thank you. 

### ISSUE THREAD

**Issue by yangjiamin** [pptam/pptam-tool#51]

**Comment by ajanes** [comment]
Sure, but please, if you work on a publication cite one of our works, e.g. https://www.sciencedirect.com/science/article/abs/pii/S016412122200142X?via%3Dihub. Thank you!

**Comment by yangjiamin** [comment]
however, I use the locust run the locustfile.py in my trainticket, there are some errors. I want to know there three locustfile.py, what's the difference about them?Thank you.
